---
title: "Zip Competition"
author: "Luana Lima"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---
```{r}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

```{r}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```


#Import Data
```{r}

install.packages("readxl")
library(readxl)

#import load data 

load <- read_excel(path  = "../ZIP_Competition/load.xlsx", sheet = 1, col_names = TRUE)
class(load$date)

#Convert to daily data

load_daily <- load %>%
  mutate(date = as.Date(date)) %>%                  
  mutate(daily_mean = rowMeans(select(., h1:h24), 
                               na.rm = TRUE)) %>%
  select(meter_id, date, daily_mean) 

#Convert to time series
load_ts <- msts(load_daily$daily_mean,
                seasonal.periods = c(7, 365.25),
                start = c(2005, 1))
```

#Train the model

```{r}
#Use data from January 1, 2005, to July 31, 2010

load_daily_2010July <- load_daily %>%
  filter(date <= as.Date("2010-07-31"))

load_daily_2010July <- msts(load_daily_2010July$daily_mean,
                     seasonal.periods = c(7, 365.25),
                     start = c(2005, 1))
n_for <- 31

#Train the data
load_ts_train <- subset(load_daily_2010July, end = length(load_daily_2010July) - n_for)

#Test
load_ts_test  <- subset(load_daily_2010July, start = length(load_daily_2010July) - n_for + 1)

autoplot(load_ts_train)
autoplot(load_ts_test)

```

Model 1 Naive Model

Step 1 Test and Record Score

```{r}
SNAIVE_test <- snaive(load_ts_train, h = n_for, holdout = FALSE)
SNAIVE_scores<- accuracy(SNAIVE_test$mean, load_ts_test)
```


Model 2: TBATS

Step 1: Test and Record Score
```{r}
# Test TBATS
TBATS_fit <- tbats(load_ts_train)
TBATS_for <- forecast(TBATS_fit, h = n_for)
TBATS_scores <- accuracy(TBATS_for$mean, load_ts_test)
```

Step 2 Compare

```{r}
# Compare with Native Model
scores <- as.data.frame(rbind(SNAIVE_scores, TBATS_scores))
row.names(scores) <- c("SNAIVE", "TBATS")
print(scores)
```

Model 3 STL+ETS

Step 1: Test and Record Score

```{r}
ETS_fit <- stlf(load_ts_train, h = n_for)
ETS_scores <- accuracy(ETS_fit$mean, load_ts_test)
```

Step 2 Compare
```{r}
# Compare
scores <- as.data.frame(rbind(SNAIVE_scores, TBATS_scores, ETS_scores))
row.names(scores) <- c("SNAIVE", "TBATS", "STL+ETS")
print(scores)
```

> TBATS has the best result.

Forecast using TBATS
```{r}
TBATS_fit_final <- tbats(load_ts)
TBATS_for_final <- forecast(TBATS_fit_final, h = 31)
```


Export Results in csv.
```{r}
submission <- data.frame(
  date = seq(as.Date("2011-07-01"), as.Date("2011-07-31"), by = "day"),
  load = as.numeric(TBATS_for_final$mean)
)

write.csv(submission, "./submission_ZIP2.csv", row.names = FALSE)
```

