% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Zip Competition},
  pdfauthor={Jingni Pang \& Zhaoxin Zhang},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Zip Competition}
\author{Jingni Pang \& Zhaoxin Zhang}
\date{}

\begin{document}
\maketitle

GitHub Repository: \url{https://github.com/ZZhang727/Pang_Zhang_ZIP}

\section{Exective Summary}\label{exective-summary}

This report is written to record the process of using R to leverage this
historical data (from January 2005 to June 2011) to forecast daily
electricity demand for July 2011. We applied different models to
forecast electricity demand in July 2010 and compared the forecasting
results with the actual data to identify the most accurate model. The
model using Prophet + TBATS had the best results. Therefore, we applied
the Prophet + TBATS model to forecast electricity load in July 2011.

\section{Section 1: Data Wrangling}\label{section-1-data-wrangling}

\subsection{1.1 Import and Convert Data}\label{import-and-convert-data}

Hourly electricity load data spanning January 2005 to June 2011 were
used to forecast daily load for July 2011. As the raw data consist of 24
hourly observations per day, daily mean load values were computed by
averaging across all hours within each calendar day, yielding a single
daily aggregate series. The resulting series was then converted to a
time series object for subsequent modeling.

\includegraphics{Pang_Zhang_FirstSubmission_files/figure-latex/unnamed-chunk-4-1.pdf}

\section{2. Methodology}\label{methodology}

The data were divided into a training set and a held-out test set. The
training set spans January 2005 through June 2010 and was used to
estimate model parameters and capture underlying temporal structure,
including trend and seasonal components. The test set comprises the
final 31 days of the sample (July 2010), which was withheld from model
fitting and used exclusively for forecast evaluation, enabling
comparison of predicted against realized daily mean load values across
models.

\includegraphics{Pang_Zhang_FirstSubmission_files/figure-latex/unnamed-chunk-6-1.pdf}
\includegraphics{Pang_Zhang_FirstSubmission_files/figure-latex/unnamed-chunk-6-2.pdf}

\section{3. Testing}\label{testing}

To evaluate forecast accuracy, each candidate model was trained on daily
mean load data from January 2005 through June 2010 and used to generate
out-of-sample forecasts for July 2010, which were then compared against
realized values using RMSE, MAE, and MAPE. A Seasonal Naïve model was
estimated as a baseline; however, it produced forecast errors,
indicating that the data exhibit temporal patterns beyond simple
seasonal repetition. Four additional specifications were subsequently
evaluated: TBATS, Neural Network (NNETAR with Fourier terms), a
TBATS--Neural Network combination, Prophet, and a TBATS--Prophet
combination. Across all accuracy metrics, the TBATS--Prophet combination
yielded the lowest errors and was selected as the final forecasting
model to predict the electricity load in July 2011.

\begin{verbatim}
##                ME     RMSE      MAE      MPE     MAPE      ACF1 Theil's U
## Test set 606.4785 950.3533 837.1102 12.34822 19.35913 0.4370708  1.772924
\end{verbatim}

\subsection{Compare Results}\label{compare-results}

\begin{verbatim}
##                     ME     RMSE      MAE       MPE     MAPE      ACF1 Theil's U
## TBAT         -37.89045 578.1685 444.7257 -3.010307 11.34223 0.4591482  1.132356
## NN           353.65717 684.3017 568.4521  6.469583 13.17944 0.5117880  1.238199
## TBATS+NN     157.88336 597.3348 479.9767  1.729638 11.62008 0.4798269  1.115130
## Prophet       19.75377 597.1820 476.8339 -1.740922 12.07137 0.4824732  1.141950
## TBAT+Prophet  -9.06834 584.2586 457.2619 -2.375614 11.62521 0.4699767  1.131892
\end{verbatim}

Among the five models evaluated, TBATS achieved the lowest RMSE
(578.17), MAE (444.73), and MAPE (11.34\%), indicating strong overall
predictive accuracy. However, its ME of -37.89 suggests a systematic
tendency to underestimate load. The TBATS--Prophet combination, while
marginally higher on RMSE (584.26) and MAE (457.26), produced a ME of
-9.07, which was the closest one to zero across all models. Therefore,
the TBATS--Prophet combination was selected as the final model.

\section{Forecast Electricity Load in July
2011}\label{forecast-electricity-load-in-july-2011}

To generate the final forecast for July 2011, both models (TBATS and
Prophet) were re-estimated on the full available training data. The
Prophet model was fitted on daily mean load data spanning January 2005
through June 2011, with weekly and yearly seasonality enabled and daily
seasonality disabled. A 31-day future dataframe was constructed using
make\_future\_dataframe(), and point forecasts were extracted from the
predicted yhat values corresponding to July 2011. In parallel, a TBATS
model was re-fitted on the complete daily mean load time series
(load\_ts) and used to generate a 31-day ahead forecast. The final
combined forecast was computed as a weighted average of the two models,
assigning a weight of 0.8 to Prophet and 0.2 to TBATS (the weight was
selected after trying different weight combinations to find the most
accurate result), yielding daily predicted load values for each day in
July 2011.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prophet\_df\_full }\OtherTok{\textless{}{-}}\NormalTok{ load\_daily }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(date, daily\_mean) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{ds =}\NormalTok{ date, }\AttributeTok{y =}\NormalTok{ daily\_mean) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(ds }\SpecialCharTok{\textless{}=} \FunctionTok{as.Date}\NormalTok{(}\StringTok{"2011{-}06{-}30"}\NormalTok{))}

\NormalTok{prophet\_fit\_final }\OtherTok{\textless{}{-}} \FunctionTok{prophet}\NormalTok{(prophet\_df\_full,}
                             \AttributeTok{weekly.seasonality =} \ConstantTok{TRUE}\NormalTok{,}
                             \AttributeTok{yearly.seasonality =} \ConstantTok{TRUE}\NormalTok{,}
                             \AttributeTok{daily.seasonality =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{future\_final }\OtherTok{\textless{}{-}} \FunctionTok{make\_future\_dataframe}\NormalTok{(prophet\_fit\_final, }\AttributeTok{periods =} \DecValTok{31}\NormalTok{)}
\NormalTok{prophet\_for\_final }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(prophet\_fit\_final, future\_final)}

\NormalTok{prophet\_pred\_final }\OtherTok{\textless{}{-}} \FunctionTok{tail}\NormalTok{(prophet\_for\_final}\SpecialCharTok{$}\NormalTok{yhat, }\DecValTok{31}\NormalTok{)}
\NormalTok{TBATS\_fit\_final }\OtherTok{\textless{}{-}} \FunctionTok{tbats}\NormalTok{(load\_ts)}
\NormalTok{TBATS\_for\_final }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(TBATS\_fit\_final, }\AttributeTok{h =} \DecValTok{31}\NormalTok{)}

\NormalTok{combo\_prophet\_tbats2 }\OtherTok{\textless{}{-}}\NormalTok{ (prophet\_pred\_final }\SpecialCharTok{*} \FloatTok{0.8} \SpecialCharTok{+} \FunctionTok{as.numeric}\NormalTok{(TBATS\_for\_final}\SpecialCharTok{$}\NormalTok{mean) }\SpecialCharTok{*} \FloatTok{0.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lr@{}}
\caption{Predicted Daily Load for July 2011 (TBATS +
Prophet)}\tabularnewline
\toprule\noalign{}
Date & Predicted Load \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Date & Predicted Load \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
2011-07-01 & 3804.069 \\
2011-07-02 & 3998.024 \\
2011-07-03 & 4068.858 \\
2011-07-04 & 3975.093 \\
2011-07-05 & 3944.191 \\
2011-07-06 & 3961.914 \\
2011-07-07 & 3964.915 \\
2011-07-08 & 3967.404 \\
2011-07-09 & 4150.787 \\
2011-07-10 & 4216.795 \\
2011-07-11 & 4124.079 \\
2011-07-12 & 4095.911 \\
2011-07-13 & 4115.465 \\
2011-07-14 & 4118.252 \\
2011-07-15 & 4119.694 \\
2011-07-16 & 4301.764 \\
2011-07-17 & 4364.578 \\
2011-07-18 & 4266.343 \\
2011-07-19 & 4231.842 \\
2011-07-20 & 4244.470 \\
2011-07-21 & 4239.148 \\
2011-07-22 & 4231.991 \\
2011-07-23 & 4405.489 \\
2011-07-24 & 4458.972 \\
2011-07-25 & 4350.616 \\
2011-07-26 & 4306.269 \\
2011-07-27 & 4309.504 \\
2011-07-28 & 4294.975 \\
2011-07-29 & 4279.171 \\
2011-07-30 & 4444.740 \\
2011-07-31 & 4490.670 \\
\end{longtable}

\end{document}
